//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VME.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VME.RecursosLocalizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de....
        /// </summary>
        internal static string acercaDe {
            get {
                return ResourceManager.GetString("acercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acerca de.
        /// </summary>
        internal static string acercaDe1 {
            get {
                return ResourceManager.GetString("acercaDe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aciertos:.
        /// </summary>
        internal static string Aciertos {
            get {
                return ResourceManager.GetString("Aciertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altavoces.
        /// </summary>
        internal static string altavocesBienvenido {
            get {
                return ResourceManager.GetString("altavocesBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes unos grandes reflejos, !eres un lince¡.
        /// </summary>
        internal static string analisisPruebaReflejosBueno {
            get {
                return ResourceManager.GetString("analisisPruebaReflejosBueno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes muy buenos reflejos, esto deberias de mirartelo..
        /// </summary>
        internal static string analisisPruebaRelejosMalo {
            get {
                return ResourceManager.GetString("analisisPruebaRelejosMalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año de nacimiento:.
        /// </summary>
        internal static string anoDeNacimientoBienvenida {
            get {
                return ResourceManager.GetString("anoDeNacimientoBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos:.
        /// </summary>
        internal static string apellidosBienvenida {
            get {
                return ResourceManager.GetString("apellidosBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        internal static string atras {
            get {
                return ResourceManager.GetString("atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autores:.
        /// </summary>
        internal static string autores {
            get {
                return ResourceManager.GetString("autores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba de visión.
        /// </summary>
        internal static string cegueraLabelColorBienvenida {
            get {
                return ResourceManager.GetString("cegueraLabelColorBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a configuracion.
        /// </summary>
        internal static string configuracion {
            get {
                return ResourceManager.GetString("configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar cierre.
        /// </summary>
        internal static string confirmarSalir {
            get {
                return ResourceManager.GetString("confirmarSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuerpo detectado.
        /// </summary>
        internal static string cuerpoDetectado {
            get {
                return ResourceManager.GetString("cuerpoDetectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener.
        /// </summary>
        internal static string detener {
            get {
                return ResourceManager.GetString("detener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivos a utilizar.
        /// </summary>
        internal static string dispositivosUtilizarLabel {
            get {
                return ResourceManager.GetString("dispositivosUtilizarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de los altavoces.
        /// </summary>
        internal static string estadoAltavocesBienvenida {
            get {
                return ResourceManager.GetString("estadoAltavocesBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de la Kinect.
        /// </summary>
        internal static string estadoKinectBienvenida {
            get {
                return ResourceManager.GetString("estadoKinectBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del micrófono.
        /// </summary>
        internal static string estadoMicrofonoBienvenida {
            get {
                return ResourceManager.GetString("estadoMicrofonoBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de pantalla táctil.
        /// </summary>
        internal static string estadoPantallaTactilBienvenida {
            get {
                return ResourceManager.GetString("estadoPantallaTactilBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar QR.
        /// </summary>
        internal static string exportarDatos {
            get {
                return ResourceManager.GetString("exportarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallos:.
        /// </summary>
        internal static string Fallos {
            get {
                return ResourceManager.GetString("Fallos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta algún parámetro de información por introducir.
        /// </summary>
        internal static string faltanParametros {
            get {
                return ResourceManager.GetString("faltanParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Felicidades has completado la configuración inicial.
        /// </summary>
        internal static string felicidadesBienvenida {
            get {
                return ResourceManager.GetString("felicidadesBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Felicidades, has completado la prueba de reflejos.
        /// </summary>
        internal static string felicidadesPruebaReflejos {
            get {
                return ResourceManager.GetString("felicidadesPruebaReflejos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        internal static string fin {
            get {
                return ResourceManager.GetString("fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de forma satisfactoria.
        /// </summary>
        internal static string finalBienvenida {
            get {
                return ResourceManager.GetString("finalBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pruebas físicas.
        /// </summary>
        internal static string fisicoCirculoMenuPrincipal {
            get {
                return ResourceManager.GetString("fisicoCirculoMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Imagen.
        /// </summary>
        internal static string guardarImagen {
            get {
                return ResourceManager.GetString("guardarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar el idioma para activar el reconocimiento de voz..
        /// </summary>
        internal static string IdiomaVoz {
            get {
                return ResourceManager.GetString("IdiomaVoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Datos.
        /// </summary>
        internal static string importarDatos {
            get {
                return ResourceManager.GetString("importarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, coloque el QR delante de la cámara Kinect.
        /// </summary>
        internal static string informacionImportarDatos {
            get {
                return ResourceManager.GetString("informacionImportarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string iniciar {
            get {
                return ResourceManager.GetString("iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrucciones.
        /// </summary>
        internal static string Instrucciones {
            get {
                return ResourceManager.GetString("Instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A continución vamos a comprobar cómo estás de reflejos, para ello te pondremos una serie de botones (amarillos y azules) y tendras que pulsar los botones azules..
        /// </summary>
        internal static string Instrucciones1Daltonico {
            get {
                return ResourceManager.GetString("Instrucciones1Daltonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A continución vamos a comprobar cómo estás de reflejos, para ello te pondremos una serie de botones (rojos y verdes) y tendras que pulsar los botones verdes..
        /// </summary>
        internal static string instrucciones1Reflejos {
            get {
                return ResourceManager.GetString("instrucciones1Reflejos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si pulsas un botón amarillo se te contabilizará puntos negativos, si aciertas sumaras uno. La prueba se repetirá 5 veces y al final te daremos los resultados..
        /// </summary>
        internal static string Instrucciones2Daltonico {
            get {
                return ResourceManager.GetString("Instrucciones2Daltonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si pulsas un botón rojo se te contabilizará puntos negativos, si aciertas sumaras uno. La prueba se repetirá 5 veces y al final te daremos los resultados..
        /// </summary>
        internal static string instrucciones2Reflejos {
            get {
                return ResourceManager.GetString("instrucciones2Reflejos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, indique que quiere usar para realizar la prueba:.
        /// </summary>
        internal static string instrucciones3Reflejos {
            get {
                return ResourceManager.GetString("instrucciones3Reflejos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz clara.
        /// </summary>
        internal static string interfazClara {
            get {
                return ResourceManager.GetString("interfazClara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz oscura.
        /// </summary>
        internal static string interfazOscura {
            get {
                return ResourceManager.GetString("interfazOscura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kinect detectada.
        /// </summary>
        internal static string KinectDetect {
            get {
                return ResourceManager.GetString("KinectDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kinect no detectada.
        /// </summary>
        internal static string KinectNoDetect {
            get {
                return ResourceManager.GetString("KinectNoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un tipo de interfaz.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi! Select your language.
        /// </summary>
        internal static string labelBienvenida {
            get {
                return ResourceManager.GetString("labelBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola! Selecciona tu idioma.
        /// </summary>
        internal static string labelBienvenida1 {
            get {
                return ResourceManager.GetString("labelBienvenida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hablanos de ti....
        /// </summary>
        internal static string labelBienvenida3 {
            get {
                return ResourceManager.GetString("labelBienvenida3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Queremos conocerte un poco más.
        /// </summary>
        internal static string labelBienvenida4 {
            get {
                return ResourceManager.GetString("labelBienvenida4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pruebas realizadas.
        /// </summary>
        internal static string labelPruebas {
            get {
                return ResourceManager.GetString("labelPruebas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colocate sobre la línea y coloca tu mano derecha en la cabeza para continuar...
        /// </summary>
        internal static string ManoCabeza {
            get {
                return ResourceManager.GetString("ManoCabeza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro que deseas salir?.
        /// </summary>
        internal static string mensajeSalir {
            get {
                return ResourceManager.GetString("mensajeSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Micrófono.
        /// </summary>
        internal static string microfonoBienvenido {
            get {
                return ResourceManager.GetString("microfonoBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí, tengo un problema que reduce mi movilidad de forma considerable..
        /// </summary>
        internal static string movilidad2Bienvenida {
            get {
                return ResourceManager.GetString("movilidad2Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí, tengo algún tipo de minusvalía física..
        /// </summary>
        internal static string movilidad3Bienvenida {
            get {
                return ResourceManager.GetString("movilidad3Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No, pero debido a alguna razón no puedo hacer determinados esfuerzos..
        /// </summary>
        internal static string movilidad4Bienvenida {
            get {
                return ResourceManager.GetString("movilidad4Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No, no tengo ningún problema de movilidad..
        /// </summary>
        internal static string movilidad5Bienvenida {
            get {
                return ResourceManager.GetString("movilidad5Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Tienes algún problema que te dificulte la movilidad?.
        /// </summary>
        internal static string movilidadBienvenida {
            get {
                return ResourceManager.GetString("movilidadBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string nombreBienvenida {
            get {
                return ResourceManager.GetString("nombreBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la compañia:.
        /// </summary>
        internal static string nombreCompania {
            get {
                return ResourceManager.GetString("nombreCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del programa:.
        /// </summary>
        internal static string nombrePrograma {
            get {
                return ResourceManager.GetString("nombrePrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a opciones.
        /// </summary>
        internal static string opciones {
            get {
                return ResourceManager.GetString("opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso (Kg):.
        /// </summary>
        internal static string pesoBienvenida {
            get {
                return ResourceManager.GetString("pesoBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Probar.
        /// </summary>
        internal static string probar {
            get {
                return ResourceManager.GetString("probar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba de reflejos.
        /// </summary>
        internal static string Prueba1MenuPrincipalFisica {
            get {
                return ResourceManager.GetString("Prueba1MenuPrincipalFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba1MenuPrincipalPsicologica {
            get {
                return ResourceManager.GetString("Prueba1MenuPrincipalPsicologica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba2MenuPrincipalFisica {
            get {
                return ResourceManager.GetString("Prueba2MenuPrincipalFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba2MenuPrincipalPsicologica {
            get {
                return ResourceManager.GetString("Prueba2MenuPrincipalPsicologica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba3MenuPrincipalFisica {
            get {
                return ResourceManager.GetString("Prueba3MenuPrincipalFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba3MenuPrincipalPsicologica {
            get {
                return ResourceManager.GetString("Prueba3MenuPrincipalPsicologica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba4MenuPrincipalFisica {
            get {
                return ResourceManager.GetString("Prueba4MenuPrincipalFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba4MenuPrincipalPsicologica {
            get {
                return ResourceManager.GetString("Prueba4MenuPrincipalPsicologica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba5MenuPrincipalFisica {
            get {
                return ResourceManager.GetString("Prueba5MenuPrincipalFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Prueba5MenuPrincipalPsicologica {
            get {
                return ResourceManager.GetString("Prueba5MenuPrincipalPsicologica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno.
        /// </summary>
        internal static string pruebaReflejosBoton1 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dos.
        /// </summary>
        internal static string pruebaReflejosBoton2 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tres.
        /// </summary>
        internal static string pruebaReflejosBoton3 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuatro.
        /// </summary>
        internal static string pruebaReflejosBoton4 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cinco.
        /// </summary>
        internal static string pruebaReflejosBoton5 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seis.
        /// </summary>
        internal static string pruebaReflejosBoton6 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siete.
        /// </summary>
        internal static string pruebaReflejosBoton7 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocho.
        /// </summary>
        internal static string pruebaReflejosBoton8 {
            get {
                return ResourceManager.GetString("pruebaReflejosBoton8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raton.
        /// </summary>
        internal static string pruebaReflejosRaton {
            get {
                return ResourceManager.GetString("pruebaReflejosRaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tactil.
        /// </summary>
        internal static string pruebaReflejosTactil {
            get {
                return ResourceManager.GetString("pruebaReflejosTactil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pruebas psicologicas.
        /// </summary>
        internal static string psicologicoCirculoMenuPrincipal {
            get {
                return ResourceManager.GetString("psicologicoCirculoMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha reconocido el diccionario..
        /// </summary>
        internal static string ReconocimientoNoRecon {
            get {
                return ResourceManager.GetString("ReconocimientoNoRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reflejos.
        /// </summary>
        internal static string Reflexes {
            get {
                return ResourceManager.GetString("Reflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regular Kinect.
        /// </summary>
        internal static string reguKine {
            get {
                return ResourceManager.GetString("reguKine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regular Kinect.
        /// </summary>
        internal static string regularKinect {
            get {
                return ResourceManager.GetString("regularKinect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para regular la kinect debe detectar tu cuerpo de pies a cabeza.
        /// </summary>
        internal static string RegularKinectBienvenida {
            get {
                return ResourceManager.GetString("RegularKinectBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regular kinect.
        /// </summary>
        internal static string regularKinectBienvenida2 {
            get {
                return ResourceManager.GetString("regularKinectBienvenida2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éstos son tus resultados de la prueba:.
        /// </summary>
        internal static string resultadoPruebaReflejos1 {
            get {
                return ResourceManager.GetString("resultadoPruebaReflejos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir sin guardar.
        /// </summary>
        internal static string salirSinGuardar {
            get {
                return ResourceManager.GetString("salirSinGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir y guardar.
        /// </summary>
        internal static string salirYGuardar {
            get {
                return ResourceManager.GetString("salirYGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string siguiente {
            get {
                return ResourceManager.GetString("siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulsa siguiente para acceder al menú principal.
        /// </summary>
        internal static string siguienteSalirBienvenida {
            get {
                return ResourceManager.GetString("siguienteSalirBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colores.
        /// </summary>
        internal static string tabColores {
            get {
                return ResourceManager.GetString("tabColores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        internal static string tabFin {
            get {
                return ResourceManager.GetString("tabFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string tabIdioma {
            get {
                return ResourceManager.GetString("tabIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        internal static string tabInformacion {
            get {
                return ResourceManager.GetString("tabInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas Movilidad.
        /// </summary>
        internal static string tabMovilidad {
            get {
                return ResourceManager.GetString("tabMovilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tecnologia.
        /// </summary>
        internal static string tabTecnologia {
            get {
                return ResourceManager.GetString("tabTecnologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista de la interfaz.
        /// </summary>
        internal static string tabVista {
            get {
                return ResourceManager.GetString("tabVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño letra:.
        /// </summary>
        internal static string tamanoLetra {
            get {
                return ResourceManager.GetString("tamanoLetra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string tamanoSlider {
            get {
                return ResourceManager.GetString("tamanoSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión:.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion Inicial.
        /// </summary>
        internal static string VMEConfiguracionInicialTitulo {
            get {
                return ResourceManager.GetString("VMEConfiguracionInicialTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string VMEErrorTitulo {
            get {
                return ResourceManager.GetString("VMEErrorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string VMEInformacionTitulo {
            get {
                return ResourceManager.GetString("VMEInformacionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del usuario.
        /// </summary>
        internal static string VMEInformacionUsuarioTitulo {
            get {
                return ResourceManager.GetString("VMEInformacionUsuarioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reflejos.
        /// </summary>
        internal static string VMEPruebaReflejosTitulo {
            get {
                return ResourceManager.GetString("VMEPruebaReflejosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sugerencia.
        /// </summary>
        internal static string VMESugerenciaTitulo {
            get {
                return ResourceManager.GetString("VMESugerenciaTitulo", resourceCulture);
            }
        }
    }
}
